### ISSUE TITLE
ftis.common.exceptions.EmptyWorkables: No workables were passed to the proc

### ISSUE THREAD

**Issue by ribon3000** [jamesb93/ftis#11]
When trying to run 1_slicing.py I'm getting this error on Windows, WSL2 as well as Ubuntu. 

```
Traceback (most recent call last):
  File "/home/robin/ftis/examples/1_slicing.py", line 53, in <module>
    world.run()
  File "/home/robin/.local/lib/python3.10/site-packages/ftis/world.py", line 110, in run
    c.walk_chain()
  File "/home/robin/.local/lib/python3.10/site-packages/ftis/corpus.py", line 52, in walk_chain
    forward_connection.walk_chain()
  File "/home/robin/.local/lib/python3.10/site-packages/ftis/common/analyser.py", line 127, in walk_chain
    forward_connection.walk_chain()
  File "/home/robin/.local/lib/python3.10/site-packages/ftis/common/analyser.py", line 110, in walk_chain
    self.run()
  File "/home/robin/.local/lib/python3.10/site-packages/ftis/analyser/audio.py", line 70, in run
    singleproc(self.name, self.segment, self.input)
  File "/home/robin/.local/lib/python3.10/site-packages/ftis/common/proc.py", line 22, in singleproc
    raise EmptyWorkables
ftis.common.exceptions.EmptyWorkables: No workables were passed to the proc


```

EDIT: this is on the branch 'trunk' - turns out that switching to 'main' fixed the issue!

**Comment by jamesb93** [comment]
by now this code is so old, im glad you just got it running ha. Let me know if there are any other issues.
